version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
  app:
    image: my-node-app
    ports:
      - 13000:4000
