### Test-db connection
GET http://localhost:13000/test-db



//-------------------------------------
//USERS TESTS ---------------------------------------
### Gets 'users' Table
GET http://localhost:13000/users

### Instance of Users Table
POST http://localhost:13000/users
Content-Type: application/json

{
  "firstname": "Mark",
  "lastname": "Matthews",
  "username": "MarkyMark",
  "password": "pw1234"
}

### Gets single item by ID
GET http://localhost:13000/users/1

### Update item by ID
PUT http://localhost:13000/users/2
Content-Type: application/json

{
  "firstname": "Matt",
  "lastname": "Markhews",
  "username": "BlahBlah",
  "password": "pw1234"
}


### Delete item by ID
DELETE http://localhost:13000/users/2



//-------------------------------------
//ITEMS TESTS ---------------------------------------
### Gets 'items' Table
GET http://localhost:13000/items

### Instance of Items Table
POST http://localhost:13000/items
Content-Type: application/json

{
  "users_id":1,
  "itemname": "Shredded Lettuce",
  "description": "yum yum crunchy for your smashburger",
  "quantity": 234
}

### Gets single item by ID
GET http://localhost:13000/items/3

### Update item by ID
PUT http://localhost:13000/items/3
Content-Type: application/json

{
  "users_id": 1,
  "itemname": "Updated Shredded Lettuce",
  "description": "New description for shredded lettuce",
  "quantity": 300
}

### Delete item by ID
DELETE http://localhost:13000/items/2
