### Test-db connection
GET http://localhost:13000/test-db

//NEEDS TO HAPPEN ON STARTUP OF APP -----------------
### Creates Items and Users Tables
GET http://localhost:13000/setup

//USERS TESTS ---------------------------------------
### Gets 'users' Table
GET http://localhost:13000/users

### Instance of Users Table
POST http://localhost:13000/users
Content-Type: application/json

{
  "firstname": "Mark",
  "lastname": "Matthews",
  "username": "Marky Mark",
  "password": "pw1234"
}

//ITEMS TESTS ---------------------------------------
### Gets 'items' Table
GET http://localhost:13000/items

### Instance of Items Table
POST http://localhost:13000/items
Content-Type: application/json

{
  "users_id":1,
  "itemname": "Shredded Lettuce",
  "description": "yum yum crunchy for your smashburger",
  "quantity": 234
}

###