version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: itemsinventory
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      NODE_ENV: development
